### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [icy-wolf/project8#1]
_Love_ the datepicker. But it looks like when I try to submit a blank form, I get an `Internal Server Error`. I believe [this resource](http://www.w3schools.com/tags/att_input_required.asp) may help you avoid a blank form being submitted.

Let me know when it's updated and I'll take another look.

**Comment by Greenjam94** [comment]
I updated the github files and it's working on my localhost, Nicole will push to her Heroku after class.

**Comment by chrisvfritz** [comment]
Super! Just ping me when Heroku is updated as well.

**Comment by icy-wolf** [comment]
Heroku app should be updated now.

-Nicole

**Comment by chrisvfritz** [comment]
A couple more things I'm noticing. While I'm picking a specific day, I'm instead being shown all the holidays for the month that day is in, which isn't really the behavior I would expect.

The other thing is it looks like the form inputs are resetting each time the form submits, while it's specified in the project criteria that `every form field should always show the current parameters`. [This example](https://gist.github.com/chrisvfritz/e36ba5ebf01f86537388) may help you figure out how you can fix this problem.

Let me know when the code is updated and I'll take another look.

**Comment by Greenjam94** [comment]
Ok made those changes. Now when you select a day, only that day's holiday is shown. If you go into the URL and modify the GET request so that the day is empty (e.g. select_date=02%2F%2F2015) then the entire month's holidays will be displayed.

Form input values now match the params, your example helped a lot! It should match the criteria, I'm sorry I didn't read over that.

Nicole has updated Heroku, [please do take another look](https://whispering-lake-1057.herokuapp.com/)

**Comment by chrisvfritz** [comment]
:+1: Much better! I do also see some indentation issues I'd like fixed in future projects, but I can let it slide in this one. Details are below.

## Points of improvement for future projects

### Ruby indentation

The standard indentation for Ruby (`.rb`) files is actually with two-space soft-tabs rather than hard-tabs. See if you can update your text editor to use two-space soft-tabs for all Ruby files. If you have trouble figuring it out, [this page may be helpful](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md). If it's not, just let me know and I'll be happy to point you in the right direction.

### Inconsistent indentation

I do notice some inconsistent indentation in some files, which I'd like you to try to clean up in future projects. Let me know if you're not sure what I mean or how you'd fix it.
